Adding all the files

diff --git a/.github/workflows/ci-workflow.yaml b/.github/workflows/ci-workflow.yaml
--- a/.github/workflows/ci-workflow.yaml
+++ b/.github/workflows/ci-workflow.yaml
@@ -66,7 +66,10 @@ jobs:
           docker run -d -p 8080:8080 -v $PWD/src/test/resources:/home/wiremock --name wiremock wiremock/wiremock:2.33.1
           docker container inspect wiremock
           echo `docker container port wiremock`
-          mvn test
+          mvn test \
+          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
+          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
   
       - name: Publish Wiremock Test Results
         uses: EnricoMi/publish-unit-test-result-action@v1
@@ -84,55 +87,53 @@ jobs:
           gcloud info
           # docker push "$GAR_INFO"/"$SHIPPING_APP_NAME":"$TAG"
           gcloud builds submit --tag "$GAR_INFO"/"$SHIPPING_APP_NAME":"$TAG" shipping/
-  deploy-to-gcp-dev:
-    name: Deploy to GCP Dev Env
-    needs: [build-cart,build-catalogue,build-dispatch,build-mongo,build-mysql,build-payment,build-rabbitmq,build-ratings,build-redis,build-shipping,build-user,build-web]
-    # needs: [build-catalogue,build-shipping]
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
+  # deploy-to-gcp-dev:
+  #   name: Deploy to GCP Dev Env
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
     
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
                         
-      - name: Setup GCP Service Account
-        uses: "google-github-actions/auth@v0"
-        with:
-          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS_P }}"
+  #     - name: Setup GCP Service Account
+  #       uses: "google-github-actions/auth@v0"
+  #       with:
+  #         credentials_json: "${{ secrets.GOOGLE_CREDENTIALS_P }}"
       
-      - name: Set up Cloud SDK
-        uses: 'google-github-actions/setup-gcloud@v0'
+  #     - name: Set up Cloud SDK
+  #       uses: 'google-github-actions/setup-gcloud@v0'
 
-      - name: Call Google Cloud Deploy
-        run: |
-          cd K8s
-          date_var=`date +%m%d%y-%H%M`
-          echo "date_var=$date_var" >> $GITHUB_ENV
-          gcloud deploy releases create rel-$date_var --delivery-pipeline=robot-shop-gcp --region=us-central1
+  #     - name: Call Google Cloud Deploy
+  #       run: |
+  #         cd K8s
+  #         date_var=`date +%m%d%y-%H%M`
+  #         echo "date_var=$date_var" >> $GITHUB_ENV
+  #         gcloud deploy releases create rel-$date_var --delivery-pipeline=robot-shop-gcp --region=us-central1
       
-      - name: verify if the rollout is success
-        run: |
-          gcloud deploy rollouts describe rel-${{ env.date_var }}-to-dev-0001 --release=rel-${{ env.date_var }} --delivery-pipeline=robot-shop-gcp --region=us-central1
-          sleep 60
-          counter=0
-          while [ $counter -lt 20 ]
-          do
-          export some_val=`gcloud deploy rollouts describe rel-${{ env.date_var }}-to-dev-0001 --release=rel-${{ env.date_var }} --delivery-pipeline=robot-shop-gcp --region=us-central1 | grep state: | cut -f2 -d: | cut -d' ' -f2`
-          if [ "$some_val" == "IN_PROGRESS" ]
-          then
-            echo "Deployment in Progress Time is: `date`"
-              sleep 30
-              continue
-          elif [ "$some_val" == "SUCCEEDED" ]
-          then
-            echo "Deployment is Succeeded Time is: `date`	"
-              exit 0
-          else
-            echo "Deployment Failed Time is: `date`"
-              exit 1
-          fi
-          counter=$(( $counter + 1))
-          done
+  #     - name: verify if the rollout is success
+  #       run: |
+  #         gcloud deploy rollouts describe rel-${{ env.date_var }}-to-dev-0001 --release=rel-${{ env.date_var }} --delivery-pipeline=robot-shop-gcp --region=us-central1
+  #         sleep 60
+  #         counter=0
+  #         while [ $counter -lt 20 ]
+  #         do
+  #         export some_val=`gcloud deploy rollouts describe rel-${{ env.date_var }}-to-dev-0001 --release=rel-${{ env.date_var }} --delivery-pipeline=robot-shop-gcp --region=us-central1 | grep state: | cut -f2 -d: | cut -d' ' -f2`
+  #         if [ "$some_val" == "IN_PROGRESS" ]
+  #         then
+  #           echo "Deployment in Progress Time is: `date`"
+  #             sleep 30
+  #             continue
+  #         elif [ "$some_val" == "SUCCEEDED" ]
+  #         then
+  #             [echo "Deployment is Succeeded Time is: `date`	"]
+  #             exit 0
+  #         else
+  #           echo "Deployment Failed Time is: `date`"
+  #             exit 1
+  #         fi
+  #         counter=$(( $counter + 1))
+  #         done
 
   # run-k6-tests:
   #   name: K6 Load Test
